-- AlterTable MockEvent: add featured column
ALTER TABLE "MockEvent" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable SavedEvent: remove eventDate, add new columns
ALTER TABLE "SavedEvent" DROP COLUMN IF EXISTS "eventDate";
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "date" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "time" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "venue" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "genre" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "subGenre" TEXT;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "priceMin" DOUBLE PRECISION;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "priceMax" DOUBLE PRECISION;
ALTER TABLE "SavedEvent" ADD COLUMN IF NOT EXISTS "url" TEXT;
