-- AlterTable
ALTER TABLE "MockEvent" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "SavedEvent" DROP COLUMN "eventDate",
ADD COLUMN "name" TEXT,
ADD COLUMN "date" TEXT,
ADD COLUMN "time" TEXT,
ADD COLUMN "venue" TEXT,
ADD COLUMN "city" TEXT,
ADD COLUMN "image" TEXT,
ADD COLUMN "category" TEXT,
ADD COLUMN "genre" TEXT,
ADD COLUMN "subGenre" TEXT,
ADD COLUMN "priceMin" DOUBLE PRECISION,
ADD COLUMN "priceMax" DOUBLE PRECISION,
ADD COLUMN "url" TEXT;
